/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#c0c1ff",
        "secondary": "#c8c6c5",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#452000",
        "surface-container-highest": "#34343d",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#07006c",
        "surface-container-high": "#292932",
        "surface-container": "#1f1f27",
        "on-primary-fixed-variant": "#2f2ebe",
        "inverse-on-surface": "#303038",
        "tertiary-fixed-dim": "#ffb783",
        "surface-tint": "#c0c1ff",
        "surface-container-lowest": "#0d0d15",
        "on-tertiary-fixed": "#301400",
        "surface-bright": "#393841",
        "surface-dim": "#13131b",
        "outline": "#908fa0",
        "secondary-fixed": "#e5e2e1",
        "on-error": "#690005",
        "surface-container-low": "#1b1b23",
        "inverse-surface": "#e4e1ed",
        "on-surface": "#e4e1ed",
        "error": "#ffb4ab",
        "primary-container": "#8083ff",
        "primary-fixed-dim": "#c0c1ff",
        "background": "#13131b",
        "surface-variant": "#34343d",
        "on-secondary-fixed-variant": "#474646",
        "on-tertiary-fixed-variant": "#703700",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary-container": "#bab8b7",
        "on-primary": "#1000a9",
        "tertiary": "#ffb783",
        "on-secondary-fixed": "#1c1b1b",
        "on-tertiary": "#4f2500",
        "on-primary-container": "#0d0096",
        "secondary-container": "#4a4949",
        "inverse-primary": "#494bd6",
        "tertiary-container": "#d97721",
        "on-background": "#e4e1ed",
        "outline-variant": "#464554",
        "error-container": "#93000a",
        "surface": "#13131b",
        "on-secondary": "#313030",
        "on-surface-variant": "#c7c4d7",
        "primary-fixed": "#e1e0ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "20px",
        "unit": "4px",
        "stack-gap": "12px",
        "container-padding": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
